#!/usr/bin/env bash
# GENERATED by scripts/build.mjs — do not edit by hand, edit the source file instead (source: marketplace.config.json)
#
# Installs my own plugins plus my favourites from other repos, in Claude Code.
# Cursor has no CLI installer — see FAVOURITES.md for the Cursor route.
set -euo pipefail

# --- my marketplace ---
claude plugin marketplace add SeeWhatsOn/ai-plugin
claude plugin install watson-core@watson-ai

# --- favourite marketplaces ---
claude plugin marketplace add anthropics/claude-plugins-official
claude plugin marketplace add addyosmani/agent-skills
claude plugin marketplace add mattpocock/skills
claude plugin marketplace add humanlayer/skills
claude plugin marketplace add langfuse/Claude-Observability-Plugin
claude plugin marketplace add warpdotdev/claude-code-warp

# --- favourite plugins from those marketplaces ---
claude plugin install agent-skills@addy-agent-skills
claude plugin install mattpocock-skills@mattpocock
claude plugin install show-me@skills
claude plugin install langfuse-observability@langfuse-observability
claude plugin install warp@claude-code-warp

echo "Done. Run /plugin inside Claude Code to review what is enabled."
