#!/usr/bin/env bash
# GENERATED by scripts/build.mjs — do not edit by hand, edit the source file instead (source: marketplace.config.json)
#
# Installs my own plugins in Claude Code. Other people's plugins are listed in
# the README under "Recommended plugins" — add those by hand, when I want them.
set -euo pipefail

claude plugin marketplace add SeeWhatsOn/ai-plugin
claude plugin install watson-core@watson-ai

echo "Done. Run /plugin inside Claude Code to review what is enabled."
